name: ozi-draft
description: "OZI release draft action."
author: "Eden Ross Duff MSc <help@oziproject.dev>"
branding:
  icon: triangle
  color: green
inputs:
  github-token:
    description: "GitHub workflow-generated token"
    required: false
    default: ${{ github.token }}
  checkout-submodules:
    description: "Whether to checkout submodules as well. true, false, or recursive"
    default: true
outputs:
  drafted:
    description: "a release has been drafted"
    value: ${{ steps.draft.outputs.created }}
  tag:
    description: "release tag name"
    value: ${{ steps.version.outputs.tag }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4.2.2
    with:
      token: ${{ inputs.github-token }}
      submodules: ${{ inputs.checkout-submodules }}
      fetch-depth: 0

  - name: Python Semantic Release
    id: release
    uses: python-semantic-release/python-semantic-release@1a324000f2251a9e722e77b128bf72712653813f  # 10.0.2
    with:
      github_token: ${{ inputs.github-token }}

  - name: Pass release draft status to job
    id: draft
    env:
      CHECK: ${{ steps.release.outputs.released == 'true' }}
    run: echo "created=$CHECK" >> $GITHUB_OUTPUT
    shell: bash

  - name: Set version
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    id: version
    run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
    shell: bash

  - uses: actions/upload-artifact@v4.6.2
    if: steps.release.outputs.released == 'true' || steps.draft.outputs.created == 'true'
    with:
      include-hidden-files: true
      name: 'security2'
      path: |
        ./
        !.git/config

  - name: No release drafted      
    if: steps.release.outputs.released == 'false' || steps.draft.outputs.created == 'false'
    run: exit 1
    shell: bash
